{{- if eq .Values.rabbitmq.mode "operator" }}
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ .Release.Name }}-rabbitmq
  labels:
    {{- include "kodus.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.rabbitmq.operator.replicas | default 1 }}
  image: {{ include "kodus-common.regPrefix" . }}{{ .Values.rabbitmq.operator.image }}
  override:
    statefulSet:
      spec:
        template:
          metadata:
            labels:
              app.kubernetes.io/part-of: kodus
              app.kubernetes.io/instance: {{ .Release.Name }}
  persistence:
    storage: {{ .Values.rabbitmq.operator.storage.size | default "8Gi" }}
    {{- with .Values.rabbitmq.operator.storage.storageClass }}
    storageClassName: {{ . }}
    {{- end }}
{{- end }}
