apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "model.name" . }}
  labels:
      app: {{ include "model.name" . }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ include "model.name" . }}-pods
  template:
    metadata:
      labels:
        app: {{ include "model.name" . }}-pods
    spec:
      containers:
        - name: {{ include "model.name" . }}-pod
          image: {{ .Values.deployment.image | quote }}
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.model.port }}
            initialDelaySeconds: 90
            periodSeconds: 5
          {{ with .Values.deployment.resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{ end }}
          command:
            - bash
            - "-c"
            - "{{ include "pip.command" . }} gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS && mlflow models serve --env-manager={{ .Values.model.envManager }} --host {{ .Values.model.host }} --port {{ .Values.model.port }} {{ .Values.model.extraArgs | join " " }} -m {{ .Values.model.path }}"
          {{- if .Values.model.trackingServerUri }}
          env:
            - name: MLFLOW_TRACKING_URI
              value: {{ .Values.model.trackingServerUri | quote }}
          {{- end }}
          {{- if .Values.deployment.envFromSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.deployment.envFromSecret | quote }}
          {{- end }}
          {{- if .Values.deployment.gcloudCredentialsSecret }}
          volumeMounts:
            - name: mlflow-gcloud-credentials
              mountPath: {{ .Values.deployment.gcloudCredentialsMountPath | quote }}
              readOnly: true
          {{- end }}
      {{- if .Values.deployment.gcloudCredentialsSecret }}
      volumes:
      - name: mlflow-gcloud-credentials
        secret:
          secretName: {{ .Values.deployment.gcloudCredentialsSecret | quote }}
      {{- end }}
