apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "tracking.name" . }}
  name: {{ include "tracking.name" . }}
spec:
  ports:
  - port: {{ .Values.server.port }}
    protocol: TCP
    targetPort: {{ .Values.server.port }}
  selector:
    app: {{ include "tracking.name" . }}-pods
