stages:
  - helm-publish

.helm-publish:
  stage: helm-publish
  image:
    name: alpine/helm:latest
    entrypoint: [""]
  variables:
    CHART_NAME: ""
  script:
    - helm repo add --username ${CI_REGISTRY_USER} --password ${CI_REGISTRY_PASSWORD} charts-repo ${CI_REGISTRY}
    - helm package charts/${CHART_NAME}
    - helm push ${CHART_NAME}*.tgz charts-repo

publish-chart-k8s-f5-service:
  extends: .helm-publish
  variables:
    CHART_NAME: k8s-f5-service

publish-chart-prefect-agent:
  extends: .helm-publish
  variables:
    CHART_NAME: prefect-agent