stages:
  - helm-publish

.helm-publish:
  stage: helm-publish
  image:
    name: alpine/helm:latest
    entrypoint: [""]
  variables:
    CHART_NAME: ""
  script:
    - apk add --update curl
    - helm package charts/${CHART_NAME}
    - chart_file=$(ls -l ${CHART_NAME}*.tgz | head -n 1 | awk '{print $NF}')
    - curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@${chart_file}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts"

publish-chart-k8s-f5-service:
  extends: .helm-publish
  variables:
    CHART_NAME: k8s-f5-service

publish-chart-prefect-agent:
  extends: .helm-publish
  variables:
    CHART_NAME: prefect-agent