{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agent-sandbox-controller
  namespace: {{ include "agent-sandbox.namespace" . }}
  labels:
    {{- $labels := include "agent-sandbox.labels" . | fromYaml }}
    {{- toYaml (merge (dict) $labels .Values.metrics.serviceMonitor.additionalLabels) | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "agent-sandbox.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      scheme: http
      {{- with .Values.metrics.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
{{- end }}
