apiVersion: v1
kind: Service
metadata:
  name: {{ include "prefect-server.nameField" (merge (dict "component" "auth-proxy") .) }}
  labels: 
    {{- include "prefect-server.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: auth-proxy
  annotations:
    {{- merge .Values.auth-proxy.annotations .Values.annotations | toYaml | nindent 4 }}
spec:
  type: {{ .Values.auth-proxy.service.type }}
  ports:
    - port: {{ .Values.auth-proxy.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "prefect-server.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: auth-proxy
