{{- if and .Values.configuration (not .Values.existingConfigmap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sequin.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "sequin.labels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "sequin.tplrender" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  config.yaml: |-
    {{- include "sequin.tplrender" (dict "value" .Values.configuration "context" $) | nindent 4 }}
{{- end }}
