{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sequin.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "sequin.labels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "sequin.tplrender" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  secret-key-base: {{ .Values.secretKeyBase | default (randBytes 64) | b64enc | quote }}
  vault-key: {{ .Values.vaultKey | default (randBytes 32) | b64enc | quote }}
{{- end }}
