{{- if and (not .Values.postgresql.enabled) (not .Values.externalDatabase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-externaldb" (include "sequin.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "sequin.labels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "sequin.tplrender" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  password: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
