{{- if and .Values.flux.enabled .Values.flux.imageUpdateOverwrite.enabled }}
{{- $fullName := include "base-chart.fullname" . }}
{{- $labels := include "base-chart.labels" . }}
{{- $namespace := .Values.flux.namespace | default "flux-system" }}
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
  labels:
  {{- $labels | nindent 4 }}
spec:
  interval: {{ .Values.flux.imageUpdateOverwrite.interval | default "1m" }}
  sourceRef:
    kind: GitRepository
    name: {{ .Values.flux.imageUpdateOverwrite.sourceRef.name }}
  git:
    checkout:
      ref:
        branch: {{ .Values.flux.imageUpdateOverwrite.git.branch | default "main" }}
    commit:
      author:
        email: {{ .Values.flux.imageUpdateOverwrite.git.commit.author.email | default "fluxcdbot@users.noreply.github.com" }}
        name: {{ .Values.flux.imageUpdateOverwrite.git.commit.author.name | default "fluxcdbot" }}
      messageTemplate: {{ .Values.flux.imageUpdateOverwrite.git.commit.messageTemplate | default "chore(image): update to {{range .Updated.Images}}{{println .}}{{end}}" | quote }}
    push:
      branch: {{ .Values.flux.imageUpdateOverwrite.git.branch | default "main" }}
{{- end }}
