{{- if .Values.apollo.hpa.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "prefect-server.nameField" (merge (dict "component" "apollo") .) }}-hpa
  labels: 
    {{- include "prefect-server.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: apollo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "prefect-server.nameField" (merge (dict "component" "apollo") .) }}
  minReplicas: {{ .Values.apollo.hpa.minReplicas }}
  maxReplicas: {{ .Values.apollo.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.apollo.hpa.cpuUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.apollo.hpa.memoryUtilization }}
{{- end }}