{{- if .Values.persistence.enabled }}
{{- if .Values.persistence.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  {{- if .Values.argocd.enabled }}
  annotations:
    argocd.argoproj.io/sync-options: Skip
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
{{- end }}
{{- end }}