apiVersion: v1
kind: Service
metadata:
  name: {{ include "letta.fullname" . }}
  labels:
    {{- include "letta.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "letta.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8283
      targetPort: http
      protocol: TCP
      name: http