---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: handler-api
  name: handler-api
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 80
  selector:
    app: handler-api

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: whatsapp-api
  name: whatsapp-api
spec:
  ports:
    - name: "http"
      port: 3000
      targetPort: 3000
  selector:
    app: whatsapp-api
