apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.agent.name }}
  labels:
    app.kubernetes.io/component: agent
spec:
  replicas: {{ .Values.agent.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: agent
  template:
    metadata:
      labels:
        app.kubernetes.io/component: agent
    spec:
      serviceAccountName: {{ .Values.agent.serviceAccountName }}
      containers:
        - name: agent
          image: "{{ .Values.agent.image.name }}:{{ .Values.agent.image.tag }}"
          command:
            - bash
            - "-c"
          {{- if eq .Values.agent.type "vertex" }}
            {{- if .Values.agent.vertexServiceAccount }}
            - "prefect agent vertex start --region-name {{ .Values.agent.vertexRegion }} --service-account {{ .Values.agent.vertexServiceAccount }}"
            {{- else }}
            - "prefect agent vertex start --region-name {{ .Values.agent.vertexRegion }}"
            {{- end }}
          {{- else if eq .Values.agent.type "kubernetes" }}
            {{- if .Values.agent.jobTemplateFilePath }}
            - "prefect agent kubernetes start --job-template {{ .Values.agent.jobTemplateFilePath }}"
            {{- else }}
            - "prefect agent kubernetes start"
            {{- end }}
          {{- else }}
            - "echo 'Invalid agent type. Please set agent.type to either kubernetes or vertex.'"
          {{- end }}
          env:
            - name: PREFECT__CLOUD__API
              value: {{ .Values.agent.apollo_url }}
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: PREFECT__CLOUD__AGENT__LABELS
              value: {{ .Values.agent.prefectLabels | toJson | quote }}
            - name: JOB_MEM_REQUEST
              value: {{ .Values.agent.job.resources.requests.memory | quote }}
            - name: JOB_MEM_LIMIT
              value: {{ .Values.agent.job.resources.limits.memory | quote }}
            - name: JOB_CPU_REQUEST
              value: {{ .Values.agent.job.resources.requests.cpu | quote }}
            - name: JOB_CPU_LIMIT
              value: {{ .Values.agent.job.resources.limits.cpu | quote }}
            - name: SERVICE_ACCOUNT_NAME
              value: {{ .Values.agent.serviceAccountName | quote }}
            {{- if .Values.agent.prefect_backend_server }}
            - name: PREFECT__BACKEND
              value: server
            {{- end }}
            {{- if eq .Values.agent.type "vertex" }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /root/.config/gcloud/creds.json
            {{- end }}
            - name: PREFECT__CLOUD__AGENT__AGENT_ADDRESS
              value: http://0.0.0.0:8080
            {{- with .Values.agent.env }}
              {{- toYaml . | nindent 10 }}
            {{- end }}
          {{- if .Values.agent.auth_secret_name }}
          volumeMounts:
            - name: prefect-auth-toml
              mountPath: /root/.prefect/
              readOnly: true
            - name: google-application-credentials
              mountPath: /root/.config/gcloud/
              readOnly: true
          {{- end }}
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 40
          {{- with .Values.agent.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.agent.auth_secret_name }}
      volumes:
        - name: prefect-auth-toml
          secret:
            secretName: {{ .Values.agent.auth_secret_name }}
        - name: google-application-credentials
          secret:
            secretName: {{ .Values.agent.gcp_sa_secret_name }}
      {{- end }}
