apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.agent.serviceAccountName }}
  labels: 
    app.kubernetes.io/component: agent-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - batch
  - extensions
  resources:
  - jobs
  - jobs/status
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - events
  - pods
  - pods/log
  - services
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.agent.serviceAccountName }}
  labels: 
    app.kubernetes.io/component: agent-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.agent.serviceAccountName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.agent.serviceAccountName }}
