{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "midpoint.database.secretName" . }}
  labels:
    {{- include "midpoint.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.database.username | quote }}
  password: {{ .Values.database.password | quote }}
{{- end }}
---
{{- if not .Values.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "midpoint.admin.secretName" . }}
  labels:
    {{- include "midpoint.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.admin.username | quote }}
  password: {{ .Values.admin.password | quote }}
{{- end }}
