apiVersion: v1
kind: Service
metadata:
  name: {{ include "midpoint.fullname" . }}
  labels:
    {{- include "midpoint.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "midpoint.selectorLabels" . | nindent 4 }}
  ports:
    - name: gui
      port: {{ .Values.service.port }}
      targetPort: gui
      protocol: TCP
