{{- if and (ne .Values.platform "openshift") .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kodus.fullname" . }}
  labels:
    {{- include "kodus.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- $hosts := dict }}
        {{- range $name, $h := .Values.ingress.hosts }}{{- $_ := set $hosts $h.host true }}{{- end }}
        {{- range $host, $_ := $hosts }}
        - {{ $host }}
        {{- end }}
      {{- if .Values.ingress.tls.secretName }}
      secretName: {{ .Values.ingress.tls.secretName }}
      {{- end }}
  {{- end }}
  rules:
    {{- range $name, $h := .Values.ingress.hosts }}
    - host: {{ $h.host }}
      http:
        paths:
          - path: {{ $h.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "kodus-common.serviceFullname" (dict "root" $ "serviceName" $h.serviceName) }}
                port:
                  name: http
    {{- end }}
{{- end }}
