# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: id-dados-rio
  namespace: {{ .Values.namespace.name | quote }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: id-dados-rio
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: id-dados-rio
    spec:
      containers:
        - name: id-dados-rio
          image: {{ .Values.deployment.image | quote }}
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: {{ .Values.deployment.envFromSecret | quote }}
          livenessProbe:
            exec:
              command:
                - bash
                - "-c"
                - kill -0 $(cat /run/nginx.pid)
            initialDelaySeconds: 5
            periodSeconds: 10
          {{ with .Values.deployment.resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{ end }}
      restartPolicy: Always
