{{- if and .Values.secret.create .Values.secret.serviceAccountKey (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudsql-proxy.fullname" . }}-credentials
  labels:
    {{- include "cloudsql-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secret.key }}: {{ .Values.secret.serviceAccountKey | b64enc }}
{{- end }}
