{{- range $instance := .Values.instances }}
{{- $ctx := dict "root" $ "instance" $instance }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudsql-proxy.instanceName" $ctx }}
  labels:
    {{- include "cloudsql-proxy.instanceLabels" $ctx | nindent 4 }}
  {{- with $.Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ default (include "cloudsql-proxy.instancePort" $ctx) $.Values.service.port }}
      targetPort: db
      protocol: TCP
      name: db
  selector:
    {{- include "cloudsql-proxy.instanceLabels" $ctx | nindent 4 }}
---
{{- end }}
